import Head from "next/head";
import React from "react";
import { products } from "./products_db";

//Pages
import Card from "./Cards";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="flex items-center justify-center bg-grey">
          <Card />
        </div>
      </main>
    </>
  );
}
